### ISSUE TITLE
String Replacement

### ISSUE THREAD

**Issue by BlairAltland** [BlairAltland/hue-calendar#6]
At some point in the next week, we need to replace all of the strings with values from the strings folder. We should also probably organize the file because it is pretty messy at this point.

**Comment by bargokr** [comment]
I can handle all of the organization since I will be going through and evaluating the design of the application around the same time.

**Comment by BlairAltland** [comment]
I believe I have replaced about 99% of the strings. We will do one final sweep on Sunday to ensure that there haven't been any which are overlooked.
