### ISSUE TITLE
Design and Splash Screen

### ISSUE THREAD

**Issue by bargokr** [BlairAltland/hue-calendar#7]
The theme, colors, and overall design will be altered and customized along with ensuring that usability is there. On top of that, I am developing a splash screen that will last only a few seconds before the app is loaded.

**Comment by BlairAltland** [comment]
Method 1.
http://blog.grafixartist.com/onboarding-android-viewpager-google-way/

Method 2.
https://github.com/PaoloRotolo/AppIntro

Method 3. 
http://saulmm.github.io/avoding-android-cold-starts

**Comment by BlairAltland** [comment]
Closed: Additional functionally will be added in the future such as an onboarding screen
